// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZq0cqSST9Lcjm-HKTY4AcZob9hcQAfg',
    appId: '1:867949138773:web:b1b9e4326837d05b2615dc',
    messagingSenderId: '867949138773',
    projectId: 'flutterapp-b3d9e',
    authDomain: 'flutterapp-b3d9e.firebaseapp.com',
    storageBucket: 'flutterapp-b3d9e.firebasestorage.app',
    measurementId: 'G-CKXTDKCPKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1bwyGp4huLpYux7A3lekCFfoGjK3eOzs',
    appId: '1:867949138773:android:7fef4dcc5c498cc42615dc',
    messagingSenderId: '867949138773',
    projectId: 'flutterapp-b3d9e',
    storageBucket: 'flutterapp-b3d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJPhojrsNrIoMHHFHOnDCniWijQ4VyRRM',
    appId: '1:867949138773:ios:a2a1c579bcdebecc2615dc',
    messagingSenderId: '867949138773',
    projectId: 'flutterapp-b3d9e',
    storageBucket: 'flutterapp-b3d9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJPhojrsNrIoMHHFHOnDCniWijQ4VyRRM',
    appId: '1:867949138773:ios:a2a1c579bcdebecc2615dc',
    messagingSenderId: '867949138773',
    projectId: 'flutterapp-b3d9e',
    storageBucket: 'flutterapp-b3d9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiZq0cqSST9Lcjm-HKTY4AcZob9hcQAfg',
    appId: '1:867949138773:web:986f17e9a4f864e12615dc',
    messagingSenderId: '867949138773',
    projectId: 'flutterapp-b3d9e',
    authDomain: 'flutterapp-b3d9e.firebaseapp.com',
    storageBucket: 'flutterapp-b3d9e.firebasestorage.app',
    measurementId: 'G-JNLNVBPW0C',
  );
}
